
name: Kotlin Script Execution

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-lastest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Run Kotlin Script
        uses: sureshg/kts-exec@v2.7
        with:
          script: "main.kts"